services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - db-network

  mongo-db:
    image: mongo:latest
    container_name: mongo-container
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes: 
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - db-network

  cache:
    image: redis:latest
    container_name: redis_container
    restart: always
    ports: 
      - '6379:6379'
    volumes:
      - cache:/data
    networks:
      - db-network
    
  node-app:
    build: .
    container_name: node-app-container
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=development
    env_file:
      - .env 
    volumes:
      - .:/app
    networks:
      - db-network
    depends_on:
      - mysql-db
      - mongo-db
      - cache

volumes:
  mysql-data:
  mongodb_data:
  cache:

networks:
  db-network:
    driver: bridge
